### ISSUE TITLE
aufs bug creates unstoppable zombies

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-odroid#101]
* Odroid-C1+ devices with an old kernel (3.10)
* puppeteer leaving orphaned chromium processes
* systemd not properly reaping the zombie because of the old kernel

Suggested solution: backport the following kernel patch from Ben Hutchings, message 47:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812207#47

Also, backport the aufs utils patch.

See also:
* https://github.com/moby/moby/issues/18180#issuecomment-193708192
* https://github.com/moby/moby/issues/19166

Copied from https://github.com/balena-os/meta-balena/issues/1344

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g9vf)

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-odroid/pull/102

**Comment by shaunmulligan** [comment]
@ZubairLK we can close this now right?
