### ISSUE TITLE
Include snd-aloop module

### ISSUE THREAD

**Issue by petrosagg** [balena-os/balena-odroid#106]
cc @pcgeek86

**Comment by floion** [comment]
For which board?

**Comment by floion** [comment]
@pcgeek86 for which board is this module needed?

**Comment by pcgeek86** [comment]
@floion I'll find out

**Comment by jareklupinski** [comment]
Odroid XU4 https://www.hardkernel.com/shop/odroid-xu4/

**Comment by floion** [comment]
@pcgeek86 is the customer still using this board? Or have they switched to a different one? I'm asking to know if we still need to include this module in the odroid xu4 image

**Comment by pcgeek86** [comment]
@floion Yes, see response from @jareklupinski

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-odroid/pull/107

**Comment by pcgeek86** [comment]
Thanks @floion!
