### ISSUE TITLE
Bluetooth Support by including kernel Modules

### ISSUE THREAD

**Issue by tacLog** [balena-os/balena-odroid#115]
After using `cat /proc/config.gz | gunzip` to pull the following, I noticed with the help of Balena support that there are lines missing on the Odroid that are present on the Fin. 

I understand this is the kernel configuration file and the versions don't match at the top.
The fin has:
4.14.98
The Odroid has:
4.19.1

I don't have enough experience to know if that may be an issue or not. 

We need Bluetooth support for our application of this board, and including these modules seems like it might add that. 

Relevant lines that are on the Fin but not the Odroid:
```
#
# CAN USB interfaces
#
# CONFIG_CAN_EMS_USB is not set
# CONFIG_CAN_ESD_USB2 is not set
CONFIG_CAN_GS_USB=m
# CONFIG_CAN_KVASER_USB is not set
# CONFIG_CAN_PEAK_USB is not set
# CONFIG_CAN_8DEV_USB is not set
# CONFIG_CAN_MCBA_USB is not set
# CONFIG_CAN_DEBUG_DEVICES is not set
CONFIG_BT=m
CONFIG_BT_BREDR=y
CONFIG_BT_RFCOMM=m
CONFIG_BT_RFCOMM_TTY=y
CONFIG_BT_BNEP=m
CONFIG_BT_BNEP_MC_FILTER=y
CONFIG_BT_BNEP_PROTO_FILTER=y
CONFIG_BT_HIDP=m
CONFIG_BT_HS=y
CONFIG_BT_LE=y
CONFIG_BT_6LOWPAN=m
# CONFIG_BT_LEDS is not set
# CONFIG_BT_SELFTEST is not set
CONFIG_BT_DEBUGFS=y

#
# Bluetooth device drivers
#
CONFIG_BT_INTEL=m
CONFIG_BT_BCM=m
CONFIG_BT_RTL=m
CONFIG_BT_HCIBTUSB=m
CONFIG_BT_HCIBTUSB_BCM=y
CONFIG_BT_HCIBTUSB_RTL=y
# CONFIG_BT_HCIBTSDIO is not set
CONFIG_BT_HCIUART=m
CONFIG_BT_HCIUART_SERDEV=y
CONFIG_BT_HCIUART_H4=y
# CONFIG_BT_HCIUART_NOKIA is not set
# CONFIG_BT_HCIUART_BCSP is not set
# CONFIG_BT_HCIUART_ATH3K is not set
# CONFIG_BT_HCIUART_LL is not set
CONFIG_BT_HCIUART_3WIRE=y
# CONFIG_BT_HCIUART_INTEL is not set
CONFIG_BT_HCIUART_BCM=y
# CONFIG_BT_HCIUART_QCA is not set
# CONFIG_BT_HCIUART_AG6XX is not set
# CONFIG_BT_HCIUART_MRVL is not set
CONFIG_BT_HCIBCM203X=m
CONFIG_BT_HCIBPA10X=m
CONFIG_BT_HCIBFUSB=m
CONFIG_BT_HCIVHCI=m
CONFIG_BT_MRVL=m
CONFIG_BT_MRVL_SDIO=m
CONFIG_BT_ATH3K=m
CONFIG_BT_WILINK=m
```

I am going to spend the next few hours/days trying to figure if I can make these changes myself (and how to build the kernel) to make this more of a pull request, but I don't expect to be successful.

**Comment by floion** [comment]
Hi, what dongle is this? What's the chipset it uses?

**Comment by tacLog** [comment]
Hey, 
The chipset is:
CSR8510
[Amazon](https://www.amazon.com/Importer520-Bluetooth-Adapter-Raspberry-Compatible/dp/B00CG94OW8) link
lsusb shows USB code:
0a12:0001 ([link](https://wiki.ubuntu.com/HardwareSupportComponentsBluetoothUsbAdapters))

It works on the fin without issue. I can try it on a Rasberry pie 3 B+ or zero w if you want.

**Comment by tacLog** [comment]
Just to update this for anyone who follows this in the future. I got my chipsets mixed up, BCM20702A0 will be supported when this issue is fixed. CSR8510 doesn't work without proprietary firmware.
