### ISSUE TITLE
Odroid XU4s doesn't boot with v2.13.6+rev1

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-odroid#88]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_djor)

**Comment by floion** [comment]
@thgreasi the customer is not using Odroid XU4. They are using a similar hardware, but not exactly the XU4.

**Comment by floion** [comment]
Closing as per my above comment
