### ISSUE TITLE
Docker performance issues on Odroid XU4

### ISSUE THREAD

**Issue by mikesimos** [balena-os/balena-odroid#99]
More info: https://github.com/moby/moby/issues/26150
https://forums.balena.io/t/increasing-cpu-limit-cpu-shares-quota-ignored/4777/10

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_g6pf)

**Comment by kazazes** [comment]
Also, many `/sys/` files are absent on the ODROID images. Most notably in `/sys/devices/system/cpu/*`. No `cpufreq`, no `governor`, etc.

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-odroid/pull/108
This will be in 2.31.5+rev2 or newer

**Comment by levesquejf** [comment]
Does it affect Odroid-C1+ image also or only XU4?

**Comment by floion** [comment]
@levesquejf for the moment the C1 is still using odroid hardkernel at version 3.10.107
